#!/bin/bash
##########################################################
# MotileCoin masternode installer                        #
# Author Pino                                            #
# MotileCoin Donate MTaxNGgc4vueM66mxV4qfrJhuekGNJj7Ds   #
# Credit to ecs87 for original guide!                    #
# Ecs87 Donate MQXiKbw5VEantHUCgiUtkN7sQeefzWbXzZ        #
##########################################################


#System upgrade
echo "Upgrading System"
sleep 2
apt-get dist-upgrade -y && apt-get update && apt-get upgrade -y


#System Dependencies
echo "Installing Dependencies"
sleep 2
add-apt-repository ppa:bitcoin/bitcoin && apt-get update && apt-get install libdb4.8-dev libdb4.8++-dev wget nano htop git software-properties-common build-essential libtool autotools-dev pkg-config libssl-dev libboost-all-dev libevent-dev libminiupnpc-dev libgmp3-dev autoconf automake && fallocate -l 3G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && echo "vm.swappiness=10" >> /etc/sysctl.conf && echo "/swapfile none swap sw 0 0" >> /etc/fstab -y


#Install Wallet
echo "Installing Wallet"
sleep 2
mkdir MotileCore && cd MotileCore && wget https://github.com/ecs87/Motile/releases/download/1/Motiled
chmod 700 Motiled

#Make Config file
mkdir .Motile
touch .Motile/Motile.conf

#Write MotileCoin Config
echo "rpcuser=masternode
rpcpassword=YOURSUPERSAFEPASSWORD
rpcport=7217
port=7218
daemon=1
server=1
rpcallowip=127.0.0.1
testnet=0
masternode=1
masternodesoftlock=1
masternodeprivkey=YOURGENKEY" > .Motile/Motile.conf
nano .Motile/Motile.conf


#Start Server
echo "Starting Wallet"
./Motiled -daemon


# Wait for the server to come up
sleep 2

echo "Done. Enjoy your Motile Masternode."

exit 0
